/// Round-trip tests for the on-disc FLAC fixtures in `test/fixtures/`.
///
/// These tests complement the synthetic in-memory fixtures used by the
/// rest of the suite. They prove that real byte files on disc — the kind
/// a user would actually load — parse, serialise, and round-trip
/// correctly. They also verify the parser rejects the malformed fixtures
/// with the expected exception types.
///
/// The fixtures are generated by `tool/generate_fixtures.dart` and
/// committed to the repository; this test reads them directly rather
/// than regenerating on the fly.
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:dart_metaflac/dart_metaflac.dart';
import 'package:test/test.dart';

void main() {
  final fixturesDir = _fixturesDir();

  Uint8List load(String name) =>
      File('${fixturesDir.path}/$name').readAsBytesSync();

  group('valid fixtures', () {
    test('minimal.flac parses with only STREAMINFO', () {
      final doc = FlacMetadataDocument.readFromBytes(load('minimal.flac'));
      expect(doc.streamInfo, isNotNull);
      expect(doc.vorbisComment, isNull);
      expect(doc.pictures, isEmpty);
      // Minimal fixture is built with paddingSize < 0, so no padding
      // block should be present.
      expect(
        doc.blocks.any((b) => b.type == FlacBlockType.padding),
        isFalse,
      );
    });

    test('with_tags.flac exposes the four generator tags in order', () {
      final doc = FlacMetadataDocument.readFromBytes(load('with_tags.flac'));
      final vc = doc.vorbisComment;
      expect(vc, isNotNull);
      expect(vc!.comments.valuesOf('ARTIST'), equals(['Fixture Artist']));
      expect(vc.comments.valuesOf('TITLE'), equals(['Fixture Title']));
      expect(vc.comments.valuesOf('ALBUM'), equals(['Fixture Album']));
      expect(vc.comments.valuesOf('DATE'), equals(['2026']));
      expect(vc.comments.entries.length, equals(4));
    });

    test('with_picture.flac contains exactly one PICTURE block', () {
      final doc = FlacMetadataDocument.readFromBytes(load('with_picture.flac'));
      expect(doc.pictures, hasLength(1));
      final pic = doc.pictures.first;
      expect(pic.mimeType, equals('image/jpeg'));
      expect(pic.description, equals('fixture cover'));
      expect(doc.vorbisComment, isNotNull);
    });

    test('with_padding.flac contains a 4096-byte PADDING block', () {
      final doc = FlacMetadataDocument.readFromBytes(load('with_padding.flac'));
      final padding = doc.blocks.whereType<PaddingBlock>().toList();
      expect(padding, hasLength(1));
      expect(padding.first.size, equals(4096));
    });

    test('valid fixtures round-trip byte-for-byte after a no-op edit', () {
      for (final name in [
        'minimal.flac',
        'with_tags.flac',
        'with_picture.flac',
        'with_padding.flac',
      ]) {
        final original = load(name);
        final doc = FlacMetadataDocument.readFromBytes(original);
        final reserialised = doc.toBytes();
        // The metadata region must be preserved exactly (the trailing
        // audio bytes in these fixtures are fixed dummy data).
        final reparsed = FlacMetadataDocument.readFromBytes(reserialised);
        expect(
          reparsed.vorbisComment?.comments.asMultiMap(),
          equals(doc.vorbisComment?.comments.asMultiMap()),
          reason: 'round-trip mismatch for $name',
        );
      }
    });
  });

  group('malformed fixtures', () {
    test('bad_magic.flac is rejected as invalid FLAC', () {
      expect(
        () => FlacMetadataDocument.readFromBytes(
            load('malformed/bad_magic.flac')),
        throwsA(isA<InvalidFlacException>()),
      );
    });

    test('truncated_block.flac raises a FlacMetadataException', () {
      expect(
        () => FlacMetadataDocument.readFromBytes(
          load('malformed/truncated_block.flac'),
        ),
        throwsA(isA<FlacMetadataException>()),
      );
    });
  });
}

Directory _fixturesDir() {
  var dir = Directory.current;
  while (true) {
    final candidate = Directory('${dir.path}/test/fixtures');
    if (candidate.existsSync()) return candidate;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('could not find test/fixtures from $dir');
    }
    dir = parent;
  }
}
