/// One-shot script that (re)generates the on-disc FLAC fixtures under
/// `test/fixtures/`.
///
/// Run with:
///
/// ```sh
/// dart run tool/generate_fixtures.dart
/// ```
///
/// The output is deterministic — running the script twice should produce
/// byte-identical files, so `git diff test/fixtures/` after a second run
/// should be empty. Commit the generated files; CI should never have to
/// regenerate them.
///
/// The script reuses the in-memory `buildFlac` / `makeJpeg` helpers from
/// `test/test_fixtures.dart` so the fixtures stay in lock-step with the
/// synthetic fixtures used by the in-memory test suite.
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:dart_metaflac/dart_metaflac.dart';

import '../test/test_fixtures.dart';

void main() {
  final root = _findProjectRoot();
  final fixturesDir = Directory('${root.path}/test/fixtures');
  final malformedDir = Directory('${fixturesDir.path}/malformed');
  fixturesDir.createSync(recursive: true);
  malformedDir.createSync(recursive: true);

  final outputs = <String, Uint8List>{
    'minimal.flac': _buildMinimal(),
    'with_tags.flac': _buildWithTags(),
    'with_picture.flac': _buildWithPicture(),
    'with_padding.flac': _buildWithPadding(),
    'malformed/bad_magic.flac': _buildBadMagic(),
    'malformed/truncated_block.flac': _buildTruncatedBlock(),
  };

  for (final entry in outputs.entries) {
    final path = '${fixturesDir.path}/${entry.key}';
    File(path).writeAsBytesSync(entry.value);
    stdout.writeln('wrote $path (${entry.value.length} bytes)');
  }

  _writeReadme(fixturesDir);
  stdout.writeln('wrote ${fixturesDir.path}/README.md');
}

Uint8List _buildMinimal() {
  return buildFlac(paddingSize: -1);
}

Uint8List _buildWithTags() {
  return buildFlac(
    paddingSize: -1,
    vorbisComment: VorbisCommentBlock(
      comments: VorbisComments(
        vendorString: 'dart_metaflac fixture',
        entries: [
          VorbisCommentEntry(key: 'ARTIST', value: 'Fixture Artist'),
          VorbisCommentEntry(key: 'TITLE', value: 'Fixture Title'),
          VorbisCommentEntry(key: 'ALBUM', value: 'Fixture Album'),
          VorbisCommentEntry(key: 'DATE', value: '2026'),
        ],
      ),
    ),
  );
}

Uint8List _buildWithPicture() {
  return buildFlac(
    paddingSize: -1,
    vorbisComment: VorbisCommentBlock(
      comments: VorbisComments(
        vendorString: 'dart_metaflac fixture',
        entries: [
          VorbisCommentEntry(key: 'TITLE', value: 'Fixture With Picture'),
        ],
      ),
    ),
    pictures: [makeJpeg(description: 'fixture cover')],
  );
}

Uint8List _buildWithPadding() {
  return buildFlac(paddingSize: 4096);
}

Uint8List _buildBadMagic() {
  // Start from a valid minimal FLAC, then corrupt the first four magic
  // bytes so the parser rejects the file with an invalid-magic error.
  final valid = buildFlac(paddingSize: -1);
  final bytes = Uint8List.fromList(valid);
  bytes[0] = 0x58; // 'X'
  bytes[1] = 0x58; // 'X'
  bytes[2] = 0x58; // 'X'
  bytes[3] = 0x58; // 'X'
  return bytes;
}

Uint8List _buildTruncatedBlock() {
  // Valid FLAC with tags, truncated mid-VORBIS_COMMENT block. The magic
  // and STREAMINFO are intact so the parser gets past the header but
  // then fails inside the metadata block it cannot complete.
  final valid = buildFlac(
    paddingSize: -1,
    vorbisComment: VorbisCommentBlock(
      comments: VorbisComments(
        vendorString: 'dart_metaflac fixture',
        entries: [
          VorbisCommentEntry(key: 'TITLE', value: 'Truncated'),
          VorbisCommentEntry(key: 'ARTIST', value: 'Fixture'),
        ],
      ),
    ),
  );
  // Keep the 4-byte magic, the 4-byte STREAMINFO header, the 34-byte
  // STREAMINFO payload, and the 4-byte VORBIS_COMMENT header — then stop.
  // That leaves the parser at the start of a block body whose declared
  // length extends past end-of-file.
  final cutoff = 4 + 4 + 34 + 4 + 8;
  return Uint8List.fromList(valid.sublist(0, cutoff));
}

void _writeReadme(Directory fixturesDir) {
  const readme = '''
# FLAC test fixtures

These files are generated by `tool/generate_fixtures.dart` — **do not edit
them by hand**. Regenerate with:

```sh
dart run tool/generate_fixtures.dart
```

The output is deterministic, so a clean run against unchanged generator
code should produce a clean `git diff`.

## Files

| File | Description |
| ---- | ----------- |
| `minimal.flac` | Tiniest valid FLAC (STREAMINFO + one dummy frame). |
| `with_tags.flac` | Minimal + a VORBIS_COMMENT block with four tags. |
| `with_picture.flac` | Minimal + one VORBIS_COMMENT and one PICTURE block (tiny JPEG). |
| `with_padding.flac` | Minimal + a 4 KB PADDING block. |
| `malformed/bad_magic.flac` | Minimal file with its `fLaC` magic bytes overwritten. |
| `malformed/truncated_block.flac` | Valid STREAMINFO, then truncated mid-VORBIS_COMMENT. |

The generator reuses `buildFlac`, `makeJpeg`, and related helpers from
`test/test_fixtures.dart`, so these on-disc fixtures stay in lock-step
with the synthetic in-memory fixtures used by the rest of the test suite.
''';
  File('${fixturesDir.path}/README.md').writeAsStringSync(readme);
}

Directory _findProjectRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/pubspec.yaml').existsSync()) return dir;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('could not find pubspec.yaml from $dir');
    }
    dir = parent;
  }
}
